-- 1.1) Monte uma query para encontrar pares únicos de nomes e idades .
SELECT DISTINCT Nome, Idade FROM Escola.Estudantes;

-- 1.2) Quantas linhas você encontraria na query anterior?
5

-- 1.3) Monte uma query para encontrar somente os nomes únicos.
SELECT DISTINCT Nome FROM Escola.Estudantes;

-- 1.4) Quantas linhas você encontraria na query anterior?
4

-- 1.5) Monte uma query para encontrar somente as idades únicas.
SELECT DISTINCT Idade FROM Escola.Estudantes;

-- 1.6) Quantas linhas você encontraria na query anterior?
4
